### ISSUE TITLE
Documentation To-Do (ongoing)

### ISSUE THREAD

**Issue by 33mhz** [pnut-api/api-spec#26]
Let me know what you would like to be fleshed out better/explained for devs or end-users.

(updated list)
- [x] pagination (since_id, before_id, special markers...)
- [x] `include_muted=1`
- [x] how invites work (and replenish)
- [x] community guidelines for NSFW, bot vs feed vs human, invites
- [x] app streaming how-to
- [x] copy mentions (`/@username`)
- [x] markdown links (`[markdown](link.com "title")`)
- [x] what content to escape (user `name`, app `name`, file `name`)
- [x] canonical post and user URLs (`https://posts.pnut.io/{post_id}`, `https://pnut.io/@username`)
- [x] explain URI Templates (`object_id`)
- [x] give examples of scope usage
- [x] redirect URI requirements
- [x] what happens when you change a client's active status (and the process of putting an app in the directory)
- [x] avatar and cover image resolution, max size (2MB, 4MB)
- [x] allowed locales and timezones
- [x] `X-PRETTY-JSON` header
- [x] examples for every endpoint's allowed/required scopes
- [x] specify max lengths for all fields (~~messages, posts~~, less common ones...)
- [x] app stream examples
- [x] examples for each option for endpoints (e.g., files can be uploaded as multipart/form or application/json)
- [x] list of file types that are uploaded encoded as utf-8
- [x] [audio oembed specifics](https://github.com/pnut-api/object-metadata/blob/master/raw/io.pnut.core.oembed.md#fields) (only duration required...)
- [x] detail email scope

**Comment by mcdemarco** [comment]
For users, where your profile is (the canonical user URL, and that it exists, and that posts are public and where they are) seems like the most useful thing.

For devs, a list of what exactly has been renamed or moved and where would be handy.
